export const metadata = {
  title: "Disclaimer",

  description:
    "Read the disclaimer for using Beeija tools, utilities, and website content.",
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-20">

      <h1 className="text-4xl font-bold text-gray-900 mb-8">
        Disclaimer
      </h1>

      <div className="space-y-6 text-gray-700 leading-8">

        <p>
          Beeija provides online calculators, simulators, comparison tools, and planning
          utilities for informational and general-purpose use only.
        </p>

        <p>
          While we strive to keep the tools accurate and reliable,
          Beeija makes no guarantees regarding completeness,
          correctness, availability, or suitability for any specific use.
        </p>

        <p>
          Users should independently verify outputs generated by the tools
          before using them in professional, technical, financial, legal,
          or critical workflows.
        </p>

        <p>
          Beeija is not responsible for any losses, damages,
          inaccuracies, or consequences resulting from the use of the
          website or its tools.
        </p>

        <p>
          External links, references, or third-party content, if present,
          are provided for convenience only and do not imply endorsement.
        </p>

        <p>
          By using Beeija, you acknowledge and accept this disclaimer
          and agree to use the platform at your own discretion.
        </p>

      </div>

    </div>
  );
}